name: test

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Erlang and Gleam
        uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93
        with:
          otp-version: "28"
          gleam-version: "1.15.2"
          rebar3-version: "3"

      - name: Validate root and example packages
        run: bash ./scripts/validate_packages.sh
